name: app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  go_router: ^18.0.0
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  core:
    path: ../packages/core
  notes:
    path: ../packages/notes
  get_it: ^9.2.1
  freezed_annotation: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_flavorizr: ^2.5.0
  shared_preferences: ^2.5.5
  build_runner: ^2.16.0
  freezed: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
